version: '3.9'

services:
  gl_ipfs:
    container_name: gl_ipfs
    image: gildlab/ipfs-node:${GILDLAB_IPFS_NODE_CHANNEL}.ipfs
    pull_policy: always
    restart: always
    logging:
      driver: local
    # dont expose anything in particular use nginx for that
    # localhost and ephemeral ports only
    ports:
      # admin (definitely not world visible)
      - "127.0.0.1::5001"
      # p2p tcp/quic
      # - "127.0.0.1::4001"
      # - "127.0.0.1::4001/udp"
      # expose directly here for now, can use nginx in future
      # Disabling tcp due to router issues. 4001/udp is fine.
      # https://github.com/ipfs/kubo/issues/3320#issuecomment-1321103079
      # - "4001:4001"
      - "4001:4001/udp"
      # gateway
      - "127.0.0.1::8080"
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/data/ipfs:/data/ipfs
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/export:/export
    env_file:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/.env

  gl_pin:
    container_name: gl_pin
    image: gildlab/ipfs-node:${GILDLAB_IPFS_NODE_CHANNEL}.pin
    pull_policy: always
    restart: always
    logging:
      driver: local
    depends_on:
      gl_ipfs:
        condition: service_healthy
    healthcheck:
      test: nix-shell /main.sh false
      interval: 30s
      timeout: 60m
    environment:
      - IPFS_HOST=gl_ipfs
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/pin:/pin

  gl_nginx:
    container_name: gl_nginx
    image: gildlab/ipfs-node:${GILDLAB_IPFS_NODE_CHANNEL}.nginx
    pull_policy: always
    restart: always
    logging:
      driver: local
    ports:
      - "80:80"
      # p2p for ipfs
      # - "4001:4001"
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/nginx:/nginx
    depends_on:
      gl_ipfs:
        condition: service_healthy