version: '3'

services:
  ipfs:
    image: ipfs/kubo
    ports:
      - '5001:5001'
      - '8080:8080'
      - '4001:4001'
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/data/ipfs:/data/ipfs
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/export:/export
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "ipfs:ipfs.gildlab.xyz"
    depends_on:
      - ipfs
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
      - NGROK_REGION=${NGROK_REGION}
      - NGROK_HOSTNAME=${NGROK_HOSTNAME}
    depends_on:
      - nginx
