version: '3'

services:
  ipfs:
    image: gildlab/ipfs-node:ipfs
    ports:
      - "5001"
      - "8080"
      - "4001"
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/data/ipfs:/data/ipfs
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/export:/export
  nginx:
    image: gildlab/ipfs-node:nginx
    ports:
      - "80"
    depends_on:
      - ipfs
  ngrok:
    image: gildlab/ipfs-node:ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
      - NGROK_REGION=${NGROK_REGION}
      - NGROK_HOSTNAME=${NGROK_HOSTNAME}
    depends_on:
      - nginx
  pin:
    image: gildlab/ipfs-node:pin
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/pin/pin.log:/home/pin.log
    depends_on:
      - ipfs
