version: '3'

services:
  ipfs:
    container_name: gl_ipfs
    image: gildlab/ipfs-node:ipfs
    restart: always
    # https://docs.ipfs.tech/how-to/run-ipfs-inside-docker/#set-up
    ports:
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
      - "4001:4001"
    volumes:
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/data/ipfs:/data/ipfs
      - ${GILDLAB_IPFS_NODE_BASE_PATH}/volumes/ipfs/export:/export
  nginx:
    container_name: gl_nginx
    image: gildlab/ipfs-node:nginx
    restart: always
    ports:
      - "80"
    depends_on:
      - ipfs
  ngrok:
    container_name: gl_ngrok
    image: gildlab/ipfs-node:ngrok
    restart: always
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
      - NGROK_REGION=${NGROK_REGION}
      - NGROK_HOSTNAME=${NGROK_HOSTNAME}
    depends_on:
      - nginx
  pin:
    container_name: gl_pin
    image: gildlab/ipfs-node:pin
    restart: always
    healthcheck:
      test: ["CMD", "nix-shell", "/pin.sh"]
      interval: 30s