version: '3'
services:
  ipfs:
    image: ipfs/kubo
    ports:
      - '5001:5001'
      - '8080:8080'
      - '4001:4001'
    volumes:
      - ./data/ipfs:/data/ipfs
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "ipfs:ipfs.gildlab.xyz"
    depends_on:
      - ipfs
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
    depends_on:
      - nginx
  pinning:
    image: vishalkale151071/ipfs-pinning:v0.2
    volumes:
      - ./pinning.log:/home/pinning.log
    links: 
      - "ipfs:ipfs.gildlab.xyz"
    depends_on:
      - ipfs