version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ./data/ipfs:/data/ipfs
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "ipfs:ipfs.aish.xyz"
    depends_on:
      - ipfs
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
    depends_on:
      - nginx
