version: '3'
services:
  ipfs:
    image: ipfs/kubo
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '5001:5001'
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./data/ipfs:/data/ipfs
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "ipfs:ipfs.gildlab.xyz"
    depends_on:
      - ipfs
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_PORT=nginx:80
      - NGROK_HOSTNAME=gildlab-ipfs.in.ngrok.io
      - NGROK_REGION=in
    depends_on:
      - nginx
