FROM ipfs/kubo:v0.19.1

ADD ./container-init.d/001-set-allow-origin.sh /container-init.d/001-set-allow-origin.sh
RUN chmod a+x /container-init.d/001-set-allow-origin.sh /container-init.d/001-set-allow-origin.sh