name: Docker image CI

on:
  push:
    branches: [ main, develop ]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TAG_BASE: gildlab/ipfs-node

jobs:
  build:
    strategy:
      matrix:
        box: [ipfs, nginx, ngrok, pin]
        include:
          - box: ipfs
            extra: ngrok

    runs-on: ubuntu-latest
    env:
      EXTRA: ${{ matrix.extra }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t "$TAG_BASE:${{ matrix.box }}-$BRANCH" --build-arg BRANCH="$BRANCH" ./${{ matrix.box }}
          if [[ ! -z "$EXTRA" ]]
          then
            docker build -t "$TAG_BASE:${{ matrix.box }}-$BRANCH-$EXTRA" --build-arg BRANCH="$BRANCH" -f "./${{ matrix.box }}/Dockerfile.$EXTRA" ./${{ matrix.box }}
          fi
      - run: |
          docker push "$TAG_BASE:${{ matrix.box }}-$BRANCH"
          if [[ ! -z "$EXTRA" ]]
          then
            docker push "$TAG_BASE:${{ matrix.box }}-$BRANCH-$EXTRA"
          fi