name: Docker image CI

on:
  push:
    branches: [ main, develop ]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        box: [ipfs, ipfs-ngrok, nginx, ngrok, pin]
        include:
          - box: ipfs
            concurrency: ipfs
          - box: ipfs-ngrok
            concurrency: ipfs
          - concurrency: default
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ matrix.concurrency }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t gildlab/ipfs-node:${{ matrix.box }}-"$BRANCH" --build-arg BRANCH="$BRANCH" ./${{ matrix.box }}
      # - run: docker push gildlab/ipfs-node:${{ matrix.box }}-"$BRANCH"