name: Docker image CI

on:
  push:
    branches: [ main, develop ]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        box: [ipfs, ipfs-ngrok, nginx, ngrok, pin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker build -t gildlab/ipfs-node:${{ matrix.box }}-"$BRANCH" --build-arg BRANCH="$BRANCH" ./${{ matrix.box }}
      # - run: docker push gildlab/ipfs-node:${{ matrix.box }}-"$BRANCH"