name: Docker image CI

on:
  push:
    branches: [ main, develop ]

env:
  CHANNEL: ${{ github.head_ref || github.ref_name }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TAG_BASE: gildlab/ipfs-node

jobs:
  build:
    strategy:
      matrix:
        box: [ipfs, nginx, pin]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t "$TAG_BASE:$CHANNEL.${{ matrix.box }}" ./${{ matrix.box }}
      - run: |
          docker push "$TAG_BASE:$CHANNEL.${{ matrix.box }}"